### ISSUE TITLE
No working, getting not implemented exceptions

### ISSUE THREAD

**Issue by abhinovpankaj** [dj-yacine-flutter/android_x_storage#1]
hashCode:
600560390
message:
"No implementation found for method getDCIMDirectory on channel android_x_storage"
runtimeType:
Type (MissingPluginException)

**Comment by djeddi-yacine** [comment]
> hashCode: 600560390 message: "No implementation found for method getDCIMDirectory on channel android_x_storage" runtimeType: Type (MissingPluginException)

after you install the package try to close the app in emulator and start it again. because it's i plugin it need to generate the kotlin code before you use it, so you need to restart it .
try:
```sh
flutter clean
flutter run
```
